# Generated by Django 3.2.16 on 2023-02-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='we are creative and excellent team', max_length=1000),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='Excellence', max_length=100),
        ),
    ]
